var id=[
    {
        "id":"p_1",
        "name":"Shilad Sen",
        "data":{"email":"ssen@macalester.edu","department":"Math/CS","type":"person"},
        "adjacencies":[
            {
                "nodeTo":"i_5",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_11",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_12",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_15",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_4",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_1",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_2",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_14",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_9",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_6",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_8",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_3",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_7",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_13",
                "data":{"$color":"#3366FF"}
            },
            {
                "nodeTo":"i_10",
                "data":{"$color":"#3366FF"}
            }
        ]
    },
    {
        "id":"p_4",
        "name":"Diane Michelfelder",
        "data":{"email":"michelfelder@macalester.edu","department":"philosophy","type":"person","sharedInterest":["web2.0","information technology","philosophy of technology","ethics of emerging technologies","web2.0","information technology","ethics of emerging technologies","ethics of emerging technologies","philosophy of technology"],"irs":[
            {
                "first":{"class":"Interest","id":"5","normalizedText":"web20","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"web2.0"},
                "second":{"class":"Interest","id":"5","normalizedText":"web20","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"web2.0"}
            },
            {
                "first":{"class":"Interest","id":"3","normalizedText":"datamining","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"data mining"},
                "second":{"class":"Interest","id":"45","normalizedText":"informationtechnology","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"information technology"}
            },
            {
                "first":{"class":"Interest","id":"13","normalizedText":"recommendersystems","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"recommender systems"},
                "second":{"class":"Interest","id":"47","normalizedText":"philosophyoftechnology","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"philosophy of technology"}
            },
            {
                "first":{"class":"Interest","id":"13","normalizedText":"recommendersystems","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"recommender systems"},
                "second":{"class":"Interest","id":"40","normalizedText":"ethicsofemergingtechnologies","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"ethics of emerging technologies"}
            },
            {
                "first":{"class":"Interest","id":"12","normalizedText":"onlinecontributions","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online contributions"},
                "second":{"class":"Interest","id":"5","normalizedText":"web20","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"web2.0"}
            },
            {
                "first":{"class":"Interest","id":"9","normalizedText":"statistics","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"statistics"},
                "second":{"class":"Interest","id":"45","normalizedText":"informationtechnology","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"information technology"}
            },
            {
                "first":{"class":"Interest","id":"10","normalizedText":"collaborativecomputing","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"collaborative computing"},
                "second":{"class":"Interest","id":"40","normalizedText":"ethicsofemergingtechnologies","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"ethics of emerging technologies"}
            },
            {
                "first":{"class":"Interest","id":"5","normalizedText":"web20","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"web2.0"},
                "second":{"class":"Interest","id":"40","normalizedText":"ethicsofemergingtechnologies","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"ethics of emerging technologies"}
            },
            {
                "first":{"class":"Interest","id":"15","normalizedText":"tagging","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"tagging"},
                "second":{"class":"Interest","id":"47","normalizedText":"philosophyoftechnology","people":[
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"philosophy of technology"}
            }
        ],"unmodifiedId":"4"},
        "adjacencies":[
            {
                "nodeTo":"i_5",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_3",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_13",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_13",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_12",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_9",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_10",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_5",
                "data":{"$color":"#CC33FF"}
            },
            {
                "nodeTo":"i_15",
                "data":{"$color":"#CC33FF"}
            }
        ]
    },
    {
        "id":"p_10",
        "name":"Kendrick Brown",
        "data":{"email":"brown@macalester.edu","department":"psychology","type":"person","sharedInterest":["social psychology","online surveys","social psychology","social psychology","online surveys"],"irs":[
            {
                "first":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"},
                "second":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"}
            },
            {
                "first":{"class":"Interest","id":"12","normalizedText":"onlinecontributions","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online contributions"},
                "second":{"class":"Interest","id":"140","normalizedText":"onlinesurveys","people":[
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"online surveys"}
            },
            {
                "first":{"class":"Interest","id":"14","normalizedText":"socialnetworks","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networks"},
                "second":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"}
            },
            {
                "first":{"class":"Interest","id":"2","normalizedText":"socialnetworking","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networking"},
                "second":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"}
            },
            {
                "first":{"class":"Interest","id":"5","normalizedText":"web20","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":4
                    }
                ],"text":"web2.0"},
                "second":{"class":"Interest","id":"140","normalizedText":"onlinesurveys","people":[
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"online surveys"}
            }
        ],"unmodifiedId":"10"},
        "adjacencies":[
            {
                "nodeTo":"i_7",
                "data":{"$color":"#FF3366"}
            },
            {
                "nodeTo":"i_12",
                "data":{"$color":"#FF3366"}
            },
            {
                "nodeTo":"i_14",
                "data":{"$color":"#FF3366"}
            },
            {
                "nodeTo":"i_2",
                "data":{"$color":"#FF3366"}
            },
            {
                "nodeTo":"i_5",
                "data":{"$color":"#FF3366"}
            }
        ]
    },
    {
        "id":"p_11",
        "name":"Martin Gunderson",
        "data":{"email":"gunderson@macalester.edu","department":"philosophy","type":"person","sharedInterest":["dignity"],"irs":[
            {
                "first":{"class":"Interest","id":"11","normalizedText":"moderation","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"moderation"},
                "second":{"class":"Interest","id":"156","normalizedText":"dignity","people":[
                    {
                        "class":"Person",
                        "id":11
                    }
                ],"text":"dignity"}
            }
        ],"unmodifiedId":"11"},
        "adjacencies":[
            {
                "nodeTo":"i_11",
                "data":{"$color":"#33FF66"}
            }
        ]
    },
    {
        "id":"p_2",
        "name":"Jaine Strauss",
        "data":{"email":"strauss@macalester.edu","department":"Psychology","type":"person","sharedInterest":["community psychology","structural analysis of social behavior (SASB)","structural analysis of social behavior (SASB)","public health","community psychology"],"irs":[
            {
                "first":{"class":"Interest","id":"1","normalizedText":"onlinecommunities","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online communities"},
                "second":{"class":"Interest","id":"28","normalizedText":"communitypsychology","people":[
                    {
                        "class":"Person",
                        "id":2
                    }
                ],"text":"community psychology"}
            },
            {
                "first":{"class":"Interest","id":"3","normalizedText":"datamining","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"data mining"},
                "second":{"class":"Interest","id":"23","normalizedText":"structuralanalysisofsocialbehaviorsasb","people":[
                    {
                        "class":"Person",
                        "id":2
                    }
                ],"text":"structural analysis of social behavior (SASB)"}
            },
            {
                "first":{"class":"Interest","id":"9","normalizedText":"statistics","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"statistics"},
                "second":{"class":"Interest","id":"23","normalizedText":"structuralanalysisofsocialbehaviorsasb","people":[
                    {
                        "class":"Person",
                        "id":2
                    }
                ],"text":"structural analysis of social behavior (SASB)"}
            },
            {
                "first":{"class":"Interest","id":"12","normalizedText":"onlinecontributions","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online contributions"},
                "second":{"class":"Interest","id":"27","normalizedText":"publichealth","people":[
                    {
                        "class":"Person",
                        "id":2
                    }
                ],"text":"public health"}
            },
            {
                "first":{"class":"Interest","id":"8","normalizedText":"grouppsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"group psychology"},
                "second":{"class":"Interest","id":"28","normalizedText":"communitypsychology","people":[
                    {
                        "class":"Person",
                        "id":2
                    }
                ],"text":"community psychology"}
            }
        ],"unmodifiedId":"2"},
        "adjacencies":[
            {
                "nodeTo":"i_1",
                "data":{"$color":"#006633"}
            },
            {
                "nodeTo":"i_3",
                "data":{"$color":"#006633"}
            },
            {
                "nodeTo":"i_9",
                "data":{"$color":"#006633"}
            },
            {
                "nodeTo":"i_12",
                "data":{"$color":"#006633"}
            },
            {
                "nodeTo":"i_8",
                "data":{"$color":"#006633"}
            }
        ]
    },
    {
        "id":"p_5",
        "name":"Dianna Shandy",
        "data":{"email":"shandy@macalester.edu","department":"anthropology","type":"person","sharedInterest":["rapid social change","rapid social change","rapid social change","immigrants","qualitative research methods","qualitative research methods"],"irs":[
            {
                "first":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"},
                "second":{"class":"Interest","id":"65","normalizedText":"rapidsocialchange","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"rapid social change"}
            },
            {
                "first":{"class":"Interest","id":"14","normalizedText":"socialnetworks","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networks"},
                "second":{"class":"Interest","id":"65","normalizedText":"rapidsocialchange","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"rapid social change"}
            },
            {
                "first":{"class":"Interest","id":"2","normalizedText":"socialnetworking","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networking"},
                "second":{"class":"Interest","id":"65","normalizedText":"rapidsocialchange","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"rapid social change"}
            },
            {
                "first":{"class":"Interest","id":"1","normalizedText":"onlinecommunities","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online communities"},
                "second":{"class":"Interest","id":"62","normalizedText":"immigrants","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"immigrants"}
            },
            {
                "first":{"class":"Interest","id":"13","normalizedText":"recommendersystems","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"recommender systems"},
                "second":{"class":"Interest","id":"64","normalizedText":"qualitativeresearchmethods","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"qualitative research methods"}
            },
            {
                "first":{"class":"Interest","id":"4","normalizedText":"machinelearning","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"machine learning"},
                "second":{"class":"Interest","id":"64","normalizedText":"qualitativeresearchmethods","people":[
                    {
                        "class":"Person",
                        "id":5
                    }
                ],"text":"qualitative research methods"}
            }
        ],"unmodifiedId":"5"},
        "adjacencies":[
            {
                "nodeTo":"i_7",
                "data":{"$color":"#003366"}
            },
            {
                "nodeTo":"i_14",
                "data":{"$color":"#003366"}
            },
            {
                "nodeTo":"i_2",
                "data":{"$color":"#003366"}
            },
            {
                "nodeTo":"i_1",
                "data":{"$color":"#003366"}
            },
            {
                "nodeTo":"i_13",
                "data":{"$color":"#003366"}
            },
            {
                "nodeTo":"i_4",
                "data":{"$color":"#003366"}
            }
        ]
    },
    {
        "id":"p_3",
        "name":"Arjun Guneratne",
        "data":{"email":"guneratne@macalester.edu","department":"anthropology","type":"person","sharedInterest":["politics","nationalism","ethnicity"],"irs":[
            {
                "first":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"},
                "second":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"}
            },
            {
                "first":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"},
                "second":{"class":"Interest","id":"33","normalizedText":"nationalism","people":[
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"nationalism"}
            },
            {
                "first":{"class":"Interest","id":"1","normalizedText":"onlinecommunities","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online communities"},
                "second":{"class":"Interest","id":"29","normalizedText":"ethnicity","people":[
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"ethnicity"}
            }
        ],"unmodifiedId":"3"},
        "adjacencies":[
            {
                "nodeTo":"i_6",
                "data":{"$color":"#A30052"}
            },
            {
                "nodeTo":"i_6",
                "data":{"$color":"#A30052"}
            },
            {
                "nodeTo":"i_1",
                "data":{"$color":"#A30052"}
            }
        ]
    },
    {
        "id":"p_9",
        "name":"Karine Moe",
        "data":{"email":"moe@macalester.edu","department":"economics","type":"person","sharedInterest":["social movements","social movements","social movements","informal economy","informal economy"],"irs":[
            {
                "first":{"class":"Interest","id":"7","normalizedText":"socialpsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":10
                    }
                ],"text":"social psychology"},
                "second":{"class":"Interest","id":"131","normalizedText":"socialmovements","people":[
                    {
                        "class":"Person",
                        "id":9
                    }
                ],"text":"social movements"}
            },
            {
                "first":{"class":"Interest","id":"14","normalizedText":"socialnetworks","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networks"},
                "second":{"class":"Interest","id":"131","normalizedText":"socialmovements","people":[
                    {
                        "class":"Person",
                        "id":9
                    }
                ],"text":"social movements"}
            },
            {
                "first":{"class":"Interest","id":"2","normalizedText":"socialnetworking","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"social networking"},
                "second":{"class":"Interest","id":"131","normalizedText":"socialmovements","people":[
                    {
                        "class":"Person",
                        "id":9
                    }
                ],"text":"social movements"}
            },
            {
                "first":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"},
                "second":{"class":"Interest","id":"128","normalizedText":"informaleconomy","people":[
                    {
                        "class":"Person",
                        "id":9
                    }
                ],"text":"informal economy"}
            },
            {
                "first":{"class":"Interest","id":"1","normalizedText":"onlinecommunities","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"online communities"},
                "second":{"class":"Interest","id":"128","normalizedText":"informaleconomy","people":[
                    {
                        "class":"Person",
                        "id":9
                    }
                ],"text":"informal economy"}
            }
        ],"unmodifiedId":"9"},
        "adjacencies":[
            {
                "nodeTo":"i_7",
                "data":{"$color":"#666600"}
            },
            {
                "nodeTo":"i_14",
                "data":{"$color":"#666600"}
            },
            {
                "nodeTo":"i_2",
                "data":{"$color":"#666600"}
            },
            {
                "nodeTo":"i_6",
                "data":{"$color":"#666600"}
            },
            {
                "nodeTo":"i_1",
                "data":{"$color":"#666600"}
            }
        ]
    },
    {
        "id":"p_7",
        "name":"Janet Folina",
        "data":{"email":"folina@macalester.edu","department":"philosophy","type":"person","sharedInterest":["visual information","visual information"],"irs":[
            {
                "first":{"class":"Interest","id":"3","normalizedText":"datamining","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"data mining"},
                "second":{"class":"Interest","id":"100","normalizedText":"visualinformation","people":[
                    {
                        "class":"Person",
                        "id":7
                    }
                ],"text":"visual information"}
            },
            {
                "first":{"class":"Interest","id":"9","normalizedText":"statistics","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"statistics"},
                "second":{"class":"Interest","id":"100","normalizedText":"visualinformation","people":[
                    {
                        "class":"Person",
                        "id":7
                    }
                ],"text":"visual information"}
            }
        ],"unmodifiedId":"7"},
        "adjacencies":[
            {
                "nodeTo":"i_3",
                "data":{"$color":"#660000"}
            },
            {
                "nodeTo":"i_9",
                "data":{"$color":"#660000"}
            }
        ]
    },
    {
        "id":"p_20",
        "name":"Franklin Hugh Adler",
        "data":{"email":"adler@macalester.edu","department":"Political Science","type":"person","sharedInterest":["comparative politics"],"irs":[
            {
                "first":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"},
                "second":{"class":"Interest","id":"214","normalizedText":"comparativepolitics","people":[
                    {
                        "class":"Person",
                        "id":20
                    }
                ],"text":"comparative politics"}
            }
        ],"unmodifiedId":"20"},
        "adjacencies":[
            {
                "nodeTo":"i_6",
                "data":{"$color":"#FF6666"}
            }
        ]
    },
    {
        "id":"p_18",
        "name":"David Chioni Moore",
        "data":{"email":"mooredc@macalester.edu","department":"International Studies and English","type":"person","sharedInterest":["African literature"],"irs":[
            {
                "first":{"class":"Interest","id":"6","normalizedText":"politics","people":[
                    {
                        "class":"Person",
                        "id":1
                    },
                    {
                        "class":"Person",
                        "id":3
                    }
                ],"text":"politics"},
                "second":{"class":"Interest","id":"200","normalizedText":"africanliterature","people":[
                    {
                        "class":"Person",
                        "id":18
                    }
                ],"text":"African literature"}
            }
        ],"unmodifiedId":"18"},
        "adjacencies":[
            {
                "nodeTo":"i_6",
                "data":{"$color":"#FFFF66"}
            }
        ]
    },
    {
        "id":"p_19",
        "name":"Dan Flath",
        "data":{"email":"flath@macalester.edu","department":"Math/CS","type":"person","sharedInterest":["algebra"],"irs":[
            {
                "first":{"class":"Interest","id":"8","normalizedText":"grouppsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"group psychology"},
                "second":{"class":"Interest","id":"211","normalizedText":"algebra","people":[
                    {
                        "class":"Person",
                        "id":19
                    }
                ],"text":"algebra"}
            }
        ],"unmodifiedId":"19"},
        "adjacencies":[
            {
                "nodeTo":"i_8",
                "data":{"$color":"#CC33FF"}
            }
        ]
    },
    {
        "id":"p_13",
        "name":"Erik Larson",
        "data":{"email":"larsone@macalester.edu","department":"Sociology","type":"person","sharedInterest":["indigenous peoples' movements"],"irs":[
            {
                "first":{"class":"Interest","id":"8","normalizedText":"grouppsychology","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"group psychology"},
                "second":{"class":"Interest","id":"169","normalizedText":"indigenouspeoplesmovements","people":[
                    {
                        "class":"Person",
                        "id":13
                    }
                ],"text":"indigenous peoples' movements"}
            }
        ],"unmodifiedId":"13"},
        "adjacencies":[
            {
                "nodeTo":"i_8",
                "data":{"$color":"#FF3366"}
            }
        ]
    },
    {
        "id":"p_17",
        "name":"Susan Eileen Fox",
        "data":{"email":"fox@macalester.edu","department":"Math/CS","type":"person","sharedInterest":["robotics"],"irs":[
            {
                "first":{"class":"Interest","id":"10","normalizedText":"collaborativecomputing","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"collaborative computing"},
                "second":{"class":"Interest","id":"198","normalizedText":"robotics","people":[
                    {
                        "class":"Person",
                        "id":17
                    }
                ],"text":"robotics"}
            }
        ],"unmodifiedId":"17"},
        "adjacencies":[
            {
                "nodeTo":"i_10",
                "data":{"$color":"#33FF66"}
            }
        ]
    },
    {
        "id":"p_6",
        "name":"Geoff Gorham",
        "data":{"email":"ggorham@macalester.edu","department":"philosophy","type":"person","sharedInterest":["quantum"],"irs":[
            {
                "first":{"class":"Interest","id":"10","normalizedText":"collaborativecomputing","people":[
                    {
                        "class":"Person",
                        "id":1
                    }
                ],"text":"collaborative computing"},
                "second":{"class":"Interest","id":"82","normalizedText":"quantum","people":[
                    {
                        "class":"Person",
                        "id":6
                    }
                ],"text":"quantum"}
            }
        ],"unmodifiedId":"6"},
        "adjacencies":[
            {
                "nodeTo":"i_10",
                "data":{"$color":"#006633"}
            }
        ]
    },
    {
        "id":"i_5",
        "name":"web2.0",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_10",
                "data":{}
            }
        ]
    },
    {
        "id":"i_11",
        "name":"moderation",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_11",
                "data":{}
            }
        ]
    },
    {
        "id":"i_12",
        "name":"online contributions",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_10",
                "data":{}
            },
            {
                "nodeTo":"p_2",
                "data":{}
            }
        ]
    },
    {
        "id":"i_15",
        "name":"tagging",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            }
        ]
    },
    {
        "id":"i_4",
        "name":"machine learning",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            }
        ]
    },
    {
        "id":"i_1",
        "name":"online communities",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_2",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            },
            {
                "nodeTo":"p_3",
                "data":{}
            },
            {
                "nodeTo":"p_9",
                "data":{}
            }
        ]
    },
    {
        "id":"i_2",
        "name":"social networking",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_10",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            },
            {
                "nodeTo":"p_9",
                "data":{}
            }
        ]
    },
    {
        "id":"i_14",
        "name":"social networks",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_10",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            },
            {
                "nodeTo":"p_9",
                "data":{}
            }
        ]
    },
    {
        "id":"i_9",
        "name":"statistics",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_2",
                "data":{}
            },
            {
                "nodeTo":"p_7",
                "data":{}
            }
        ]
    },
    {
        "id":"i_6",
        "name":"politics",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_3",
                "data":{}
            },
            {
                "nodeTo":"p_3",
                "data":{}
            },
            {
                "nodeTo":"p_9",
                "data":{}
            },
            {
                "nodeTo":"p_20",
                "data":{}
            },
            {
                "nodeTo":"p_18",
                "data":{}
            }
        ]
    },
    {
        "id":"i_8",
        "name":"group psychology",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_2",
                "data":{}
            },
            {
                "nodeTo":"p_19",
                "data":{}
            },
            {
                "nodeTo":"p_13",
                "data":{}
            }
        ]
    },
    {
        "id":"i_3",
        "name":"data mining",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_2",
                "data":{}
            },
            {
                "nodeTo":"p_7",
                "data":{}
            }
        ]
    },
    {
        "id":"i_7",
        "name":"social psychology",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_10",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            },
            {
                "nodeTo":"p_9",
                "data":{}
            }
        ]
    },
    {
        "id":"i_13",
        "name":"recommender systems",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_5",
                "data":{}
            }
        ]
    },
    {
        "id":"i_10",
        "name":"collaborative computing",
        "data":{"type":"interest"},
        "adjacencies":[
            {
                "nodeTo":"p_1",
                "data":{}
            },
            {
                "nodeTo":"p_4",
                "data":{}
            },
            {
                "nodeTo":"p_17",
                "data":{}
            },
            {
                "nodeTo":"p_6",
                "data":{}
            }
        ]
    }
]